title: Dauntless Noob Data Scientist
author: Akash Mhaske
email: binary13@live.com
description: > # this means to ignore newlines until "baseurl:"
  This is a my AI ML  portfolio, Hope this adds value to your life

# social links
twitter_username: binary13 # DO NOT include the @ character, or else the build will fail!
github_username:  thecuriosky # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
